//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CProductId { get; set; }
        public string CProductName { get; set; }
        public string CProductDescription { get; set; }
        public Nullable<double> CProductPrice { get; set; }
        public string CProductImgId { get; set; }
    
        public virtual Protable Protable { get; set; }
    }
}
