//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protable
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string ProductImgId { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
